apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: yogiman/akka-http-playground
    docker:
      buildArgs:
        JAR_FILE: target/scala-2.12/akkahttp-quickstart-assembly-0.1.jar
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
